In [2]:
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import os

In [3]:
model = load_model('D:\Deep Learning\FaceMaskDetector\maskdetector.model')

In [4]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         input_2[0][0]                    
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, 112, 112, 32) 0           bn_Conv1[0][0]                   
____________________________________________________________________________________________

In [5]:
prototxtPath = os.path.sep.join([r'D:\Deep Learning\FaceMaskDetector\face detector', 'deploy.prototxt'])
weightsPath = os.path.sep.join([r'D:\Deep Learning\FaceMaskDetector\face detector', 'res10_300x300_ssd_iter_140000.caffemodel'])

In [6]:
prototxtPath

'D:\\Deep Learning\\FaceMaskDetector\\face detector\\deploy.prototxt'

In [7]:
weightsPath

'D:\\Deep Learning\\FaceMaskDetector\\face detector\\res10_300x300_ssd_iter_140000.caffemodel'

In [8]:
#Reads the network model (stored in two variables: prototxtPath, weightsPath) in Caffe framework's format.
faceNet = cv2.dnn.readNet(prototxtPath, weightsPath) # facedetector

In [9]:
faceNet

<dnn_Net 000001FB9A3ECCF0>

In [10]:
img = cv2.imread('D:\Deep Learning\FaceMaskDetector\images\image-4.jpeg')

In [11]:
img

array([[[245, 254, 233],
        [216, 241, 243],
        [195, 239, 255],
        ...,
        [234, 235, 233],
        [234, 235, 233],
        [234, 235, 233]],

       [[245, 253, 236],
        [221, 246, 250],
        [192, 236, 255],
        ...,
        [234, 235, 233],
        [234, 235, 233],
        [234, 235, 233]],

       [[243, 252, 239],
        [228, 251, 255],
        [186, 229, 255],
        ...,
        [234, 235, 233],
        [234, 235, 233],
        [234, 235, 233]],

       ...,

       [[ 32,  69, 113],
        [ 26,  63, 107],
        [ 18,  55,  99],
        ...,
        [209, 206, 198],
        [209, 206, 198],
        [208, 205, 197]],

       [[  0,  36,  80],
        [  0,  37,  81],
        [  2,  39,  83],
        ...,
        [208, 205, 197],
        [208, 205, 197],
        [207, 204, 196]],

       [[ 20,  57, 101],
        [ 23,  60, 104],
        [ 27,  64, 108],
        ...,
        [208, 205, 197],
        [207, 204, 196],
        [207, 204, 196]]

In [12]:
img.shape

(182, 277, 3)

In [13]:
(h,w) = img.shape[:2]

In [14]:
(h,w)

(182, 277)

In [15]:
#get our blob which is our input image
blob = cv2.dnn.blobFromImage(img, 1.0, (300,300), (104.0, 177.0, 123.0))

In [16]:
blob

array([[[[ 141.,  115.,   95., ...,  130.,  130.,  130.],
         [ 141.,  117.,   94., ...,  130.,  130.,  130.],
         [ 141.,  120.,   93., ...,  130.,  130.,  130.],
         ...,
         [-103., -104., -102., ...,  104.,  104.,  103.],
         [ -92.,  -91.,  -88., ...,  104.,  103.,  103.],
         [ -84.,  -82.,  -78., ...,  104.,  103.,  103.]],

        [[  77.,   65.,   62., ...,   58.,   58.,   58.],
         [  77.,   67.,   62., ...,   58.,   58.,   58.],
         [  76.,   70.,   61., ...,   58.,   58.,   58.],
         ...,
         [-141., -140., -138., ...,   28.,   28.,   27.],
         [-129., -127., -124., ...,   28.,   27.,   27.],
         [-120., -118., -114., ...,   28.,   27.,   27.]],

        [[ 110.,  119.,  129., ...,  110.,  110.,  110.],
         [ 111.,  121.,  130., ...,  110.,  110.,  110.],
         [ 113.,  125.,  131., ...,  110.,  110.,  110.],
         ...,
         [ -43.,  -42.,  -40., ...,   74.,   74.,   73.],
         [ -31.,  -29.,  -

In [15]:
blob.shape

(1, 3, 300, 300)

In [17]:
#input the blob into the model and get back the detections 
faceNet.setInput(blob)
detections = faceNet.forward()

In [18]:
detections[0]

array([[[0.        , 1.        , 0.96561384, ..., 0.32786888,
         0.6966748 , 0.58485925],
        [0.        , 1.        , 0.8606308 , ..., 0.16102737,
         0.4170705 , 0.4433155 ],
        [0.        , 1.        , 0.12880942, ..., 4.002889  ,
         4.836928  , 4.9875197 ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]], dtype=float32)

In [19]:
print(detections.shape)
print(detections.shape[2])

(1, 1, 200, 7)
200


In [20]:
detections[0,0,:,2]

array([0.96561384, 0.8606308 , 0.12880942, 0.12792015, 0.12420268,
       0.12173712, 0.11767729, 0.11303754, 0.10803648, 0.10744338,
       0.10406545, 0.10339834, 0.10313897, 0.10239781, 0.10168858,
       0.10017106, 0.09670562, 0.09643073, 0.0962429 , 0.09427021,
       0.09392221, 0.09289169, 0.09275701, 0.0924975 , 0.09228075,
       0.0920594 , 0.09150507, 0.09098344, 0.09053875, 0.09051719,
       0.08911267, 0.08869765, 0.08855218, 0.08780833, 0.08668964,
       0.08664362, 0.08637851, 0.08612216, 0.08590094, 0.08551231,
       0.08495304, 0.08487113, 0.08438887, 0.08411432, 0.08402011,
       0.08394648, 0.08344329, 0.08298762, 0.08298314, 0.08268801,
       0.08247916, 0.08226211, 0.08222558, 0.0822234 , 0.08209589,
       0.08207264, 0.08178187, 0.08174149, 0.08144879, 0.08110751,
       0.08102192, 0.08084159, 0.08081686, 0.08053005, 0.08034792,
       0.08032115, 0.08020301, 0.07986905, 0.07975809, 0.0797412 ,
       0.07967667, 0.07954609, 0.0795223 , 0.07952157, 0.07943

In [21]:
for i in range(0, detections.shape[2]):
    confidence = detections[0, 0, i, 2]
    
# Extract confidence and compare it to the confidence threshold(50%) so that we can filter out detections that are weak.
# If the algorithm is more than 50% confident that the detection is a face, Iterate over all of the faces detected and extract their start and end points.

    if (confidence > 0.5):
        box = detections[0, 0, i, 3:7]*np.array([w,h,w,h])
        startX, startY, endX, endY = box.astype('int')
        
        # ensure the bounding boxes fall within the dimensions of the frame
        startX, startY = (max(0, startX), max(0,startY))
        endX, endY = (min(w-1, endX), min(h-1, endY))
        
        # extract the face ROI, convert it from BGR to RGB channel, resize it to 224,224 and preprocess it
        face = img[startY:endY, startX:endX]
        face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
        face = cv2.resize(face, (224,224))
        face = img_to_array(face)
        face = preprocess_input(face)
        face = np.expand_dims(face, axis=0)
        
        withMask, withoutMask = model.predict(face)[0]
        
        # determine the class label and color(the class label and the bounding box will be shown in the specified color)
        label = "Mask" if withMask > withoutMask else "No Mask"
        color = (0,255,0) if label=='Mask' else (0,0,255)
        
        label="{}: {:.2f}%".format(label,max(withMask,withoutMask)*100)
 
   
# If the algorithm is more than 50% confident that the detection is a face, show a rectangle around it .
# display the label(mask or withoutmask) and rectagular bounding boxes around the face
        cv2.putText(img, label, (startX, startY-10), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
        cv2.rectangle(img, (startX, startY), (endX, endY), color, 2)
        

cv2.imshow("Output", img)
cv2.waitKey(0)
cv2.destroyAllWindows()